---
- name: Install MongoDB 8.0 Community Edition on Ubuntu 22.04
  hosts: all
  become: true

  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - gnupg
          - curl
          - ca-certificates
        state: present
        update_cache: yes

    - name: Add MongoDB 8.0 GPG key
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
        gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg
      args:
        creates: /usr/share/keyrings/mongodb-server-8.0.gpg

    - name: Add MongoDB 8.0 APT repository
      copy:
        dest: /etc/apt/sources.list.d/mongodb-org-8.0.list
        content: |
          deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse

    - name: Reload APT cache after adding MongoDB repo
      apt:
        update_cache: yes

    - name: Install MongoDB 8.0
      apt:
        name: mongodb-org
        state: present

    - name: Enable and start MongoDB
      systemd:
        name: mongod
        enabled: yes
        state: started

    - name: Wait for MongoDB to be available
      wait_for:
        port: 27017
        state: started
        timeout: 30
