---

- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - nfs-common 
      
    state: latest



- name: Use the k8s apt key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"
    
- name: PRE Install k8s apt sources
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
    state: present

- name: Install containerd package
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate default containerd config file
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Set SystemdCgroup to true in containerd config file
  replace:
    path: /etc/containerd/config.toml
    regexp: '(^\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'

- name: Disable swap immediately
  command: swapoff -a
  when: ansible_swaptotal_mb is defined and ansible_swaptotal_mb | int > 0

- name: Comment out swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '#\1'

- name: Ensure net.ipv4.ip_forward is enabled in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^\s*#?\s*net\.ipv4\.ip_forward'
    line: 'net.ipv4.ip_forward = 1'

- name: Create /etc/modules-load.d/k8s.conf with br_netfilter module
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
    create: yes

- name: Reboot the system to apply configuration changes
  reboot:
    msg: "Reboot initiated by Ansible after system configuration changes"
    reboot_timeout: 600
